spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml

  docker:
    compose:
      enabled:
        false

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update